version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8001:5432"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  docker-wkhtmltopdf-aas:
    image: "openlabs/docker-wkhtmltopdf-aas"
    ports:
      - "80:80"
